### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by JOJ0** [grawlinson/python-discogs-api#2]
Hi,
you might not have noticed it yet but we had a similar idea in mind and are continuing to maintain the now deprecated discogs python client originally coded by discogs.com. We founded our project team around the same time as you started this repo: June 2020.

This is our repo, we already brought in some new features compared to the original client.: https://github.com/joalla/discogs_client, even some that you also seem to have merged into your fork. It would be wonderful if we could merge all the stuff together into one python package.

Also the module was packaged for Debian Linux: https://packages.debian.org/sid/python3-discogs-client, https://packages.debian.org/bullseye/python3-discogs-client and also Alpine Linux: https://pkgs.alpinelinux.org/packages?name=*discogs*&branch=edge

We would welcome you to share your thoughts in this thread on the discogs forum https://www.discogs.com/forum/thread/822690?page=1#8302473 or get in touch directly with either discogs.com user https://www.discogs.com/user/alifhughes or https://www.discogs.com/user/J0J0.

We hope to hear from you soon and maybe work on stuff together in the future :-)
all the best
Jojo & Alistair & Lambengolmo (Joalla Discogs Client Team)

**Comment by grawlinson** [comment]
I can't believe I didn't see this comment! I'm going to have stern words with my email client the next time I see it.

**Comment by grawlinson** [comment]
Some time ago, I submitted a PR in beets which replaces the official discogs client with the Joalla fork.

I just need to get around to officially deprecating this fork, as you guys are doing a wonderful job. :)

**Comment by JOJ0** [comment]
Oh I wasn't aware that Beets uses it. Nice news! Never gotten around to trying Beets since digital music organisation is it's own sience if using several digital DJing systems and adapting Beets with my workflows sounded like a lot of work. Anyway it's an awesome project and I'm happy discogs_client is used there!🙌
